/*
	Purpose: This script answer business related question using sql queries
*/

-- Explore All Countries Our customers come from.
SELECT DISTINCT
	country
FROM gold.dim_customers;

-- Explore All Categories 
SELECT DISTINCT
	category
FROM gold.dim_products;

-- Explore categories and subcategories
SELECT DISTINCT
	category,subcategory,product_name
FROM gold.dim_products;

-- Find the Date of First and Last Order
-- How many year of sales available
SELECT 
	min(order_date) as "First Order Date",
    max(order_date) as "Last Order Date",
    timestampdiff(month,min(order_date),max(order_date)) as "No of years of Sales"
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT 
	*
FROM gold.dim_customers
WHERE birthdate = (SELECT min(birthdate) FROM gold.dim_customers)
	OR birthdate = (SELECT max(birthdate) FROM gold.dim_customers);

SELECT 
	min(timestampdiff(Year,birthdate,create_date)) as "min Age",
    max(timestampdiff(Year,birthdate,create_date)) as "max Age"
FROM gold.dim_customers;

-- Find the total sales
SELECT 
	sum(sales_amount) as "Total Sales"
FROM gold.fact_sales;

-- Find how many items are sold
SELECT 
	sum(quantity) as "Total Quantity"
FROM gold.fact_sales;

-- Find the average selling price
SELECT 
	avg(sales_amount) as "Avg Sales"
FROM gold.fact_sales;

-- Find the total no of orders
SELECT 
	count(DISTINCT order_number) as "Total orders"
FROM gold.fact_sales;

-- Find the total no of products
SELECT 
	count(DISTINCT product_key) as "Total no of products"
FROM gold.dim_products;

-- find the total no of customers
SELECT 
	count(DISTINCT customer_key) as "Total no of customers"
FROM gold.dim_customers;

-- Find the total no of customers that has placed orders
SELECT 
	count(DISTINCT customer_key)
FROM gold.fact_sales;

-- All important business metrics report
SELECT "Total Sales" as measure_name, sum(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT "Total Quantity" as measure_name, sum(quantity) as measure_value FROM gold.fact_sales
UNION ALL 
SELECT "Avg Sales" as measure_name, avg(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL 
SELECT "Total orders" as measure_name, count(DISTINCT order_number) as measure_value FROM gold.fact_sales
UNION ALL 
SELECT "Total no of products" as measure_name, count(DISTINCT product_key) as measure_value FROM gold.dim_products
UNION ALL 
SELECT "Total no of customers" as measure_name, count(DISTINCT customer_key) as measure_value FROM gold.dim_customers
UNION ALL 
SELECT "Total no of customers placed order" as measure_name, count(DISTINCT customer_key) as measure_value FROM gold.fact_sales;

-- Find the total customers by countries
SELECT 
	country, count(customer_key)
FROM gold.dim_customers
group by country;

-- Find the total customers by gender
SELECT 
	gender, count(customer_key)
FROM gold.dim_customers
group by gender;

-- Find total products by category
SELECT 
	category, count(product_key)
FROM gold.dim_products
group by category;

-- What is the average cost in each category?
SELECT 
	category, avg(product_cost)
FROM gold.dim_products
group by category;

-- Revenue by catgory
SELECT 
	dp.category, SUM(sales_amount) as "Revenue"
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
group by category
ORDER BY Revenue DESC;


-- what is the total revenue generated by each customer
SELECT 
	dc.customer_key,dc.first_name,dc.last_name, SUM(sales_amount) as "Revenue"
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
group by customer_key,first_name,last_name
ORDER by Revenue DESC
LIMIT 5;


-- what is the distribution of sold items across countries?
SELECT 
	country,product_name,sum(quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON  f.customer_key = c.customer_key
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
group by country,product_name;


-- Which 5 products generate the highest revenue?
SELECT 
	product_name,sum(sales_amount) revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
group by product_name
ORDER BY revenue DESC
LIMIT 5;

SELECT *
FROM
(
	SELECT 
		product_name,sum(sales_amount) revenue,
		row_number() over(order by sum(sales_amount) DESC) AS product_rank
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON f.product_key = p.product_key
	group by product_name) as subtable
    WHERE product_rank <=5
;



-- bottom 5 products by revenue
SELECT 
	product_name,sum(sales_amount) revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
group by product_name
ORDER BY revenue ASC
LIMIT 5;


-- 3 customers with fewest orders placed
SELECT 
	dc.customer_key,dc.first_name,dc.last_name, count(DISTINCT order_number) as no_of_orders
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
group by customer_key,first_name,last_name
ORDER by no_of_orders ASC
LIMIT 3;
